os: linux

# don't install anything
install: true

script:
  - mkdir build && mv travis-freemint-1.18 build/.travis && cd build && tar cjf travis-freemint-1.18.tar.bz2 .travis && cd ..

deploy:
  edge:
    branch: v1.8.47
  provider: bintray
  file: bintray.desc
  user: mikrosk
  key:
    secure: IC2hKKh7WfWFWj75pyihwCudU02Yk28lJ5jWCL0zynkoAGg8pDwy9k+ZpIMuG95JzEJJKi3U7pscgsxPHYwq11228T9epkQpqxU3zhqne1IDZt4+z4BJ/idW6b3Z/afFLxLXjG/dzUhYy6tTM1G82FJZUBlC8XPJsbIy7DRAij2AajV+8aFUAb7VsHtiZ6tg39G3QBHvCD4ki/LaY1n5lwnu4dLUSxWb6lyW2IRtFtoNntelBSPlfcpYP8i6Og+Rxh2lYZAAZRgkXWpwRgDINc5oQcaKg1ntgYC3bgusKDYxdZ07rX4WWCwqdvlUwTQuGJ+Hq8fEZPmFXityUfW+O+Z8fxBzDp8q/8z+Tq+S+E+VDYqYCrm97i9gWN+xeocADfKej+dQHVBzrWoiadQ7FHu3aICmpnbRQNWAXf7ehS0LgavjyhNlAvXCU2jZFthmDmDd0JiVHKhvjccxp7kqrml7+mFlTBZIATM4bXvF4aOVmfOyLv6hM+O9WNRGSprPr7FmjZlz9FVG53fUHum1T43qfnfQxlXzfGeK3bZWWxsNwILU+RJKkl7JimOWLbqKhsnAoe5kldT3L9Q2nCyS8HJdDbchhyvE5XZdro3BNgW4rni6izDR8UWWRcEl+ClVqiALzLuYq0Dbj0SKFdJgk534r7lPqoriyTEOY6K1sOw=
  on: freemint-1.18-raw
